apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: pmironenko-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: postgres-db
  template:
    metadata:
      labels:
        deployment: postgres-db
        app: pmironenko-app
    spec:
      containers:
        - name: postgres-container
          image: postgres
          envFrom:
            - secretRef:
                name: app-secret
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
