apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: webimage
    newName: astrasource/devops-final
    newTag: v0.0.5

resources:
  - "db-deployment.yaml"
  - "db-service.yaml"
  - "app-deployment.yaml"
  - "app-service.yaml"
  - "namespace.yaml"
  - "configmap.yaml"
  - "secret.yaml"

namespace: pmironenko
