apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd
spec:
  dnsNames:
    - "pmironenko.dacdevops.ru"
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: pmironenko
