apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-pmironenko-ceritifcate
spec:
  dnsNames:
    - pmironenko.dacdevops.ru
  issuerRef:
    kind: ClusterIssuer
    name: yc-clusterissuer
  secretName: pmironenko-certificate
